// Generated by LiveScript 1.3.1
var fs, parseFile;
fs = require('fs');
parseFile = require('lson').parseFile;
module.exports.niceName = 'Custom file (.atom-build.json)';
module.exports.isEligable = function(path){
  return fs.existsSync(path + "/.atom-build.lson");
};
module.exports.settings = function(path){
  var realAtomBuild, build;
  realAtomBuild = fs.realpathSync(path + "/.atom-build.lson");
  delete require.cache[realAtomBuild];
  build = parseFile(realAtomBuild);
  return {
    exec: build.cmd,
    env: build.env,
    args: build.args,
    cwd: build.cwd,
    sh: build.sh,
    errorMatch: build.errorMatch
  };
};