// Generated by LiveScript 1.3.1
var fs, parseFile, join, _;
fs = require('fs');
parseFile = require('lson').parseFile;
join = require('path').join;
_ = require('lodash');
module.exports.niceName = 'Custom file (.atom-build.json)';
module.exports.isEligable = function(cwd){
  return fs.existsSync(join(cwd, '.atom-build.lson'));
};
module.exports.settings = function(cwd){
  var realAtomBuild, createBuildConfig, build, config;
  realAtomBuild = fs.realpathSync(cwd + "/.atom-build.lson");
  delete require.cache[realAtomBuild];
  createBuildConfig = function(build, name){
    return {
      name: "Custom: " + name,
      exec: build.cmd,
      env: build.env,
      args: build.args,
      cwd: build.cwd,
      sh: build.sh,
      errorMatch: build.errorMatch
    };
  };
  build = parseFile(realAtomBuild);
  config = [];
  config.push(createBuildConfig(build, build.name)) || 'default';
  _.forEach(build.targets || [], function(target, name){
    return config.push(createBuildConfig(target, name));
  });
  return config;
};